import { mkdir, writeFile } from 'node:fs/promises';

const locales = {
    en: {
        extensionName: 'Yeedio: Video Speed Controller & Volume Booster', extensionDescription: 'Control video speed up to 16x and boost volume up to 600%. Simple, fast, lightweight.',
        settings: 'Settings', speed: 'Speed', videoSpeed: 'Video speed', volumeBoost: 'Volume Boost', nowPlaying: 'Now Playing', loading: 'Loading…', checkingPage: 'Checking page…', unknownTab: 'Unknown tab', cannotAccessPage: 'Cannot access this page', noVideo: 'No video on this page', resolution: 'Resolution', detectingResolution: 'Detecting resolution…', settingsTitle: 'Yeedio Settings', savedVideoSpeed: 'Saved video speed (0.25x – 16x)', savedVolumeBoost: 'Saved volume boost (0% – 600%)', saveSettings: 'Save settings', settingsSaved: 'Settings saved.', keyboardShortcuts: 'Keyboard shortcuts', openYeedio: 'open Yeedio', adjustSpeed: 'decrease / increase speed', customizeShortcuts: 'You can customize volume shortcuts at', increaseSpeedCommand: 'Increase video speed (+0.25x)', decreaseSpeedCommand: 'Decrease video speed (-0.25x)', increaseVolumeCommand: 'Increase volume boost (+10%)', decreaseVolumeCommand: 'Decrease volume boost (-10%)'
    },
    tr: {
        extensionName: 'Yeedio: Video Hızı Kontrolü & Ses Yükseltici', extensionDescription: "Video hızını 16x'e, sesi %600'e kadar ayarlayın. Basit, hızlı ve hafif.",
        settings: 'Ayarlar', speed: 'Hız', videoSpeed: 'Video hızı', volumeBoost: 'Ses Yükseltme', nowPlaying: 'Şu An Oynatılıyor', loading: 'Yükleniyor…', checkingPage: 'Sayfa kontrol ediliyor…', unknownTab: 'Bilinmeyen sekme', cannotAccessPage: 'Bu sayfaya erişilemiyor', noVideo: 'Bu sayfada video yok', resolution: 'Çözünürlük', detectingResolution: 'Çözünürlük algılanıyor…', settingsTitle: 'Yeedio Ayarları', savedVideoSpeed: 'Kayıtlı video hızı (0.25x – 16x)', savedVolumeBoost: 'Kayıtlı ses yükseltme (%0 – %600)', saveSettings: 'Ayarları kaydet', settingsSaved: 'Ayarlar kaydedildi.', keyboardShortcuts: 'Klavye kısayolları', openYeedio: "Yeedio'yu aç", adjustSpeed: 'hızı azalt / artır', customizeShortcuts: 'Ses kısayollarını buradan değiştirebilirsiniz:', increaseSpeedCommand: 'Video hızını artır (+0.25x)', decreaseSpeedCommand: 'Video hızını azalt (-0.25x)', increaseVolumeCommand: 'Ses yükseltmeyi artır (+%10)', decreaseVolumeCommand: 'Ses yükseltmeyi azalt (-%10)'
    },
    de: {
        extensionName: 'Yeedio: Videogeschwindigkeit & Lautstärke-Booster', extensionDescription: 'Videogeschwindigkeit bis 16x und Lautstärke bis 600% steuern. Einfach, schnell und leicht.',
        settings: 'Einstellungen', speed: 'Geschwindigkeit', videoSpeed: 'Videogeschwindigkeit', volumeBoost: 'Lautstärke-Boost', nowPlaying: 'Aktuelle Wiedergabe', loading: 'Laden…', checkingPage: 'Seite wird geprüft…', unknownTab: 'Unbekannter Tab', cannotAccessPage: 'Auf diese Seite kann nicht zugegriffen werden', noVideo: 'Kein Video auf dieser Seite', resolution: 'Auflösung', detectingResolution: 'Auflösung wird erkannt…', settingsTitle: 'Yeedio-Einstellungen', savedVideoSpeed: 'Gespeicherte Videogeschwindigkeit (0,25x – 16x)', savedVolumeBoost: 'Gespeicherter Lautstärke-Boost (0% – 600%)', saveSettings: 'Einstellungen speichern', settingsSaved: 'Einstellungen gespeichert.', keyboardShortcuts: 'Tastenkürzel', openYeedio: 'Yeedio öffnen', adjustSpeed: 'Geschwindigkeit verringern / erhöhen', customizeShortcuts: 'Lautstärke-Tastenkürzel anpassen unter', increaseSpeedCommand: 'Videogeschwindigkeit erhöhen (+0,25x)', decreaseSpeedCommand: 'Videogeschwindigkeit verringern (-0,25x)', increaseVolumeCommand: 'Lautstärke-Boost erhöhen (+10%)', decreaseVolumeCommand: 'Lautstärke-Boost verringern (-10%)'
    },
    es: {
        extensionName: 'Yeedio: Velocidad de Video y Refuerzo de Volumen', extensionDescription: 'Controla la velocidad hasta 16x y aumenta el volumen hasta 600%. Simple, rápido y ligero.',
        settings: 'Ajustes', speed: 'Velocidad', videoSpeed: 'Velocidad del video', volumeBoost: 'Refuerzo de Volumen', nowPlaying: 'Reproduciendo Ahora', loading: 'Cargando…', checkingPage: 'Comprobando la página…', unknownTab: 'Pestaña desconocida', cannotAccessPage: 'No se puede acceder a esta página', noVideo: 'No hay video en esta página', resolution: 'Resolución', detectingResolution: 'Detectando resolución…', settingsTitle: 'Ajustes de Yeedio', savedVideoSpeed: 'Velocidad guardada (0,25x – 16x)', savedVolumeBoost: 'Volumen guardado (0% – 600%)', saveSettings: 'Guardar ajustes', settingsSaved: 'Ajustes guardados.', keyboardShortcuts: 'Atajos de teclado', openYeedio: 'abrir Yeedio', adjustSpeed: 'reducir / aumentar velocidad', customizeShortcuts: 'Personaliza los atajos de volumen en', increaseSpeedCommand: 'Aumentar velocidad del video (+0,25x)', decreaseSpeedCommand: 'Reducir velocidad del video (-0,25x)', increaseVolumeCommand: 'Aumentar refuerzo de volumen (+10%)', decreaseVolumeCommand: 'Reducir refuerzo de volumen (-10%)'
    },
    fr: {
        extensionName: 'Yeedio : Vitesse Vidéo et Amplificateur de Volume', extensionDescription: "Réglez la vitesse jusqu'à 16x et le volume jusqu'à 600 %. Simple, rapide et léger.",
        settings: 'Paramètres', speed: 'Vitesse', videoSpeed: 'Vitesse de la vidéo', volumeBoost: 'Amplification du Volume', nowPlaying: 'Lecture en Cours', loading: 'Chargement…', checkingPage: 'Vérification de la page…', unknownTab: 'Onglet inconnu', cannotAccessPage: 'Impossible d’accéder à cette page', noVideo: 'Aucune vidéo sur cette page', resolution: 'Résolution', detectingResolution: 'Détection de la résolution…', settingsTitle: 'Paramètres Yeedio', savedVideoSpeed: 'Vitesse enregistrée (0,25x – 16x)', savedVolumeBoost: 'Volume enregistré (0 % – 600 %)', saveSettings: 'Enregistrer', settingsSaved: 'Paramètres enregistrés.', keyboardShortcuts: 'Raccourcis clavier', openYeedio: 'ouvrir Yeedio', adjustSpeed: 'ralentir / accélérer', customizeShortcuts: 'Personnalisez les raccourcis de volume sur', increaseSpeedCommand: 'Augmenter la vitesse (+0,25x)', decreaseSpeedCommand: 'Réduire la vitesse (-0,25x)', increaseVolumeCommand: 'Augmenter le volume (+10 %)', decreaseVolumeCommand: 'Réduire le volume (-10 %)'
    },
    it: {
        extensionName: 'Yeedio: Velocità Video e Amplificatore Volume', extensionDescription: 'Controlla la velocità fino a 16x e aumenta il volume fino al 600%. Semplice, veloce e leggero.',
        settings: 'Impostazioni', speed: 'Velocità', videoSpeed: 'Velocità video', volumeBoost: 'Amplificazione Volume', nowPlaying: 'In Riproduzione', loading: 'Caricamento…', checkingPage: 'Controllo pagina…', unknownTab: 'Scheda sconosciuta', cannotAccessPage: 'Impossibile accedere a questa pagina', noVideo: 'Nessun video in questa pagina', resolution: 'Risoluzione', detectingResolution: 'Rilevamento risoluzione…', settingsTitle: 'Impostazioni Yeedio', savedVideoSpeed: 'Velocità salvata (0,25x – 16x)', savedVolumeBoost: 'Volume salvato (0% – 600%)', saveSettings: 'Salva impostazioni', settingsSaved: 'Impostazioni salvate.', keyboardShortcuts: 'Scorciatoie da tastiera', openYeedio: 'apri Yeedio', adjustSpeed: 'riduci / aumenta velocità', customizeShortcuts: 'Personalizza le scorciatoie del volume in', increaseSpeedCommand: 'Aumenta velocità video (+0,25x)', decreaseSpeedCommand: 'Riduci velocità video (-0,25x)', increaseVolumeCommand: 'Aumenta volume (+10%)', decreaseVolumeCommand: 'Riduci volume (-10%)'
    },
    pt_BR: {
        extensionName: 'Yeedio: Velocidade de Vídeo e Amplificador de Volume', extensionDescription: 'Controle a velocidade até 16x e aumente o volume até 600%. Simples, rápido e leve.',
        settings: 'Configurações', speed: 'Velocidade', videoSpeed: 'Velocidade do vídeo', volumeBoost: 'Amplificação de Volume', nowPlaying: 'Reproduzindo Agora', loading: 'Carregando…', checkingPage: 'Verificando a página…', unknownTab: 'Aba desconhecida', cannotAccessPage: 'Não é possível acessar esta página', noVideo: 'Nenhum vídeo nesta página', resolution: 'Resolução', detectingResolution: 'Detectando resolução…', settingsTitle: 'Configurações do Yeedio', savedVideoSpeed: 'Velocidade salva (0,25x – 16x)', savedVolumeBoost: 'Volume salvo (0% – 600%)', saveSettings: 'Salvar configurações', settingsSaved: 'Configurações salvas.', keyboardShortcuts: 'Atalhos de teclado', openYeedio: 'abrir o Yeedio', adjustSpeed: 'diminuir / aumentar velocidade', customizeShortcuts: 'Personalize os atalhos de volume em', increaseSpeedCommand: 'Aumentar velocidade (+0,25x)', decreaseSpeedCommand: 'Diminuir velocidade (-0,25x)', increaseVolumeCommand: 'Aumentar volume (+10%)', decreaseVolumeCommand: 'Diminuir volume (-10%)'
    },
    ru: {
        extensionName: 'Yeedio: Скорость Видео и Усилитель Громкости', extensionDescription: 'Скорость видео до 16x и громкость до 600%. Просто, быстро и легко.',
        settings: 'Настройки', speed: 'Скорость', videoSpeed: 'Скорость видео', volumeBoost: 'Усиление Громкости', nowPlaying: 'Сейчас Играет', loading: 'Загрузка…', checkingPage: 'Проверка страницы…', unknownTab: 'Неизвестная вкладка', cannotAccessPage: 'Нет доступа к странице', noVideo: 'На странице нет видео', resolution: 'Разрешение', detectingResolution: 'Определение разрешения…', settingsTitle: 'Настройки Yeedio', savedVideoSpeed: 'Сохранённая скорость (0,25x – 16x)', savedVolumeBoost: 'Сохранённая громкость (0% – 600%)', saveSettings: 'Сохранить', settingsSaved: 'Настройки сохранены.', keyboardShortcuts: 'Горячие клавиши', openYeedio: 'открыть Yeedio', adjustSpeed: 'уменьшить / увеличить скорость', customizeShortcuts: 'Настройте клавиши громкости на', increaseSpeedCommand: 'Увеличить скорость (+0,25x)', decreaseSpeedCommand: 'Уменьшить скорость (-0,25x)', increaseVolumeCommand: 'Увеличить громкость (+10%)', decreaseVolumeCommand: 'Уменьшить громкость (-10%)'
    },
    ja: {
        extensionName: 'Yeedio: 動画速度・音量ブースター', extensionDescription: '動画速度を16倍、音量を600%まで調整。シンプルで高速、軽量です。',
        settings: '設定', speed: '速度', videoSpeed: '動画の速度', volumeBoost: '音量ブースト', nowPlaying: '再生中', loading: '読み込み中…', checkingPage: 'ページを確認中…', unknownTab: '不明なタブ', cannotAccessPage: 'このページにアクセスできません', noVideo: 'このページに動画がありません', resolution: '解像度', detectingResolution: '解像度を検出中…', settingsTitle: 'Yeedio 設定', savedVideoSpeed: '保存した動画速度 (0.25x – 16x)', savedVolumeBoost: '保存した音量 (0% – 600%)', saveSettings: '設定を保存', settingsSaved: '設定を保存しました。', keyboardShortcuts: 'キーボードショートカット', openYeedio: 'Yeedio を開く', adjustSpeed: '速度を下げる / 上げる', customizeShortcuts: '音量ショートカットの設定:', increaseSpeedCommand: '動画速度を上げる (+0.25x)', decreaseSpeedCommand: '動画速度を下げる (-0.25x)', increaseVolumeCommand: '音量ブーストを上げる (+10%)', decreaseVolumeCommand: '音量ブーストを下げる (-10%)'
    },
    ko: {
        extensionName: 'Yeedio: 동영상 배속 및 볼륨 부스터', extensionDescription: '동영상 속도를 16배, 볼륨을 600%까지 조절하세요. 간단하고 빠르며 가볍습니다.',
        settings: '설정', speed: '속도', videoSpeed: '동영상 속도', volumeBoost: '볼륨 부스트', nowPlaying: '재생 중', loading: '로딩 중…', checkingPage: '페이지 확인 중…', unknownTab: '알 수 없는 탭', cannotAccessPage: '이 페이지에 접근할 수 없습니다', noVideo: '이 페이지에 동영상이 없습니다', resolution: '해상도', detectingResolution: '해상도 감지 중…', settingsTitle: 'Yeedio 설정', savedVideoSpeed: '저장된 동영상 속도 (0.25x – 16x)', savedVolumeBoost: '저장된 볼륨 (0% – 600%)', saveSettings: '설정 저장', settingsSaved: '설정이 저장되었습니다.', keyboardShortcuts: '키보드 단축키', openYeedio: 'Yeedio 열기', adjustSpeed: '속도 낮추기 / 높이기', customizeShortcuts: '볼륨 단축키 설정:', increaseSpeedCommand: '동영상 속도 높이기 (+0.25x)', decreaseSpeedCommand: '동영상 속도 낮추기 (-0.25x)', increaseVolumeCommand: '볼륨 부스트 높이기 (+10%)', decreaseVolumeCommand: '볼륨 부스트 낮추기 (-10%)'
    },
    zh_CN: {
        extensionName: 'Yeedio：视频速度与音量增强器', extensionDescription: '视频速度最高16倍，音量最高600%。简单、快速且轻量。',
        settings: '设置', speed: '速度', videoSpeed: '视频速度', volumeBoost: '音量增强', nowPlaying: '正在播放', loading: '加载中…', checkingPage: '正在检查页面…', unknownTab: '未知标签页', cannotAccessPage: '无法访问此页面', noVideo: '此页面没有视频', resolution: '分辨率', detectingResolution: '正在检测分辨率…', settingsTitle: 'Yeedio 设置', savedVideoSpeed: '已保存的视频速度 (0.25x – 16x)', savedVolumeBoost: '已保存的音量 (0% – 600%)', saveSettings: '保存设置', settingsSaved: '设置已保存。', keyboardShortcuts: '键盘快捷键', openYeedio: '打开 Yeedio', adjustSpeed: '降低 / 提高速度', customizeShortcuts: '在此设置音量快捷键：', increaseSpeedCommand: '提高视频速度 (+0.25x)', decreaseSpeedCommand: '降低视频速度 (-0.25x)', increaseVolumeCommand: '提高音量增强 (+10%)', decreaseVolumeCommand: '降低音量增强 (-10%)'
    },
    ar: {
        extensionName: 'Yeedio: سرعة الفيديو ومضخم الصوت', extensionDescription: 'تحكم في سرعة الفيديو حتى 16x والصوت حتى 600%. بسيط وسريع وخفيف.',
        settings: 'الإعدادات', speed: 'السرعة', videoSpeed: 'سرعة الفيديو', volumeBoost: 'تضخيم الصوت', nowPlaying: 'يعمل الآن', loading: 'جارٍ التحميل…', checkingPage: 'جارٍ فحص الصفحة…', unknownTab: 'علامة تبويب غير معروفة', cannotAccessPage: 'تعذر الوصول إلى هذه الصفحة', noVideo: 'لا يوجد فيديو في هذه الصفحة', resolution: 'الدقة', detectingResolution: 'جارٍ اكتشاف الدقة…', settingsTitle: 'إعدادات Yeedio', savedVideoSpeed: 'سرعة الفيديو المحفوظة (0.25x – 16x)', savedVolumeBoost: 'مستوى الصوت المحفوظ (0% – 600%)', saveSettings: 'حفظ الإعدادات', settingsSaved: 'تم حفظ الإعدادات.', keyboardShortcuts: 'اختصارات لوحة المفاتيح', openYeedio: 'فتح Yeedio', adjustSpeed: 'خفض / زيادة السرعة', customizeShortcuts: 'خصص اختصارات الصوت في', increaseSpeedCommand: 'زيادة سرعة الفيديو (+0.25x)', decreaseSpeedCommand: 'خفض سرعة الفيديو (-0.25x)', increaseVolumeCommand: 'زيادة الصوت (+10%)', decreaseVolumeCommand: 'خفض الصوت (-10%)'
    },
    hi: {
        extensionName: 'Yeedio: वीडियो स्पीड और वॉल्यूम बूस्टर', extensionDescription: 'वीडियो गति 16x और वॉल्यूम 600% तक कंट्रोल करें। सरल, तेज़ और हल्का।',
        settings: 'सेटिंग्स', speed: 'गति', videoSpeed: 'वीडियो गति', volumeBoost: 'वॉल्यूम बूस्ट', nowPlaying: 'अभी चल रहा है', loading: 'लोड हो रहा है…', checkingPage: 'पेज जाँचा जा रहा है…', unknownTab: 'अज्ञात टैब', cannotAccessPage: 'इस पेज को ऐक्सेस नहीं कर सकते', noVideo: 'इस पेज पर कोई वीडियो नहीं', resolution: 'रिज़ॉल्यूशन', detectingResolution: 'रिज़ॉल्यूशन पहचाना जा रहा है…', settingsTitle: 'Yeedio सेटिंग्स', savedVideoSpeed: 'सहेजी गई वीडियो गति (0.25x – 16x)', savedVolumeBoost: 'सहेजा गया वॉल्यूम (0% – 600%)', saveSettings: 'सेटिंग्स सहेजें', settingsSaved: 'सेटिंग्स सहेजी गईं।', keyboardShortcuts: 'कीबोर्ड शॉर्टकट', openYeedio: 'Yeedio खोलें', adjustSpeed: 'गति घटाएँ / बढ़ाएँ', customizeShortcuts: 'वॉल्यूम शॉर्टकट यहाँ बदलें:', increaseSpeedCommand: 'वीडियो गति बढ़ाएँ (+0.25x)', decreaseSpeedCommand: 'वीडियो गति घटाएँ (-0.25x)', increaseVolumeCommand: 'वॉल्यूम बढ़ाएँ (+10%)', decreaseVolumeCommand: 'वॉल्यूम घटाएँ (-10%)'
    },
    id: {
        extensionName: 'Yeedio: Pengatur Kecepatan Video & Penguat Volume', extensionDescription: 'Atur kecepatan video hingga 16x dan volume hingga 600%. Sederhana, cepat, dan ringan.',
        settings: 'Setelan', speed: 'Kecepatan', videoSpeed: 'Kecepatan video', volumeBoost: 'Penguat Volume', nowPlaying: 'Sedang Diputar', loading: 'Memuat…', checkingPage: 'Memeriksa halaman…', unknownTab: 'Tab tidak dikenal', cannotAccessPage: 'Tidak dapat mengakses halaman ini', noVideo: 'Tidak ada video di halaman ini', resolution: 'Resolusi', detectingResolution: 'Mendeteksi resolusi…', settingsTitle: 'Setelan Yeedio', savedVideoSpeed: 'Kecepatan video tersimpan (0,25x – 16x)', savedVolumeBoost: 'Volume tersimpan (0% – 600%)', saveSettings: 'Simpan setelan', settingsSaved: 'Setelan disimpan.', keyboardShortcuts: 'Pintasan keyboard', openYeedio: 'buka Yeedio', adjustSpeed: 'kurangi / tambah kecepatan', customizeShortcuts: 'Sesuaikan pintasan volume di', increaseSpeedCommand: 'Tambah kecepatan video (+0,25x)', decreaseSpeedCommand: 'Kurangi kecepatan video (-0,25x)', increaseVolumeCommand: 'Tambah penguat volume (+10%)', decreaseVolumeCommand: 'Kurangi penguat volume (-10%)'
    },
    nl: {
        extensionName: 'Yeedio: Videosnelheid & Volumeversterker', extensionDescription: 'Regel videosnelheid tot 16x en versterk volume tot 600%. Eenvoudig, snel en lichtgewicht.',
        settings: 'Instellingen', speed: 'Snelheid', videoSpeed: 'Videosnelheid', volumeBoost: 'Volumeversterking', nowPlaying: 'Wordt Nu Afgespeeld', loading: 'Laden…', checkingPage: 'Pagina controleren…', unknownTab: 'Onbekend tabblad', cannotAccessPage: 'Geen toegang tot deze pagina', noVideo: 'Geen video op deze pagina', resolution: 'Resolutie', detectingResolution: 'Resolutie detecteren…', settingsTitle: 'Yeedio-instellingen', savedVideoSpeed: 'Opgeslagen videosnelheid (0,25x – 16x)', savedVolumeBoost: 'Opgeslagen volume (0% – 600%)', saveSettings: 'Instellingen opslaan', settingsSaved: 'Instellingen opgeslagen.', keyboardShortcuts: 'Sneltoetsen', openYeedio: 'Yeedio openen', adjustSpeed: 'snelheid verlagen / verhogen', customizeShortcuts: 'Pas volumesneltoetsen aan op', increaseSpeedCommand: 'Videosnelheid verhogen (+0,25x)', decreaseSpeedCommand: 'Videosnelheid verlagen (-0,25x)', increaseVolumeCommand: 'Volume verhogen (+10%)', decreaseVolumeCommand: 'Volume verlagen (-10%)'
    },
    pl: {
        extensionName: 'Yeedio: Prędkość Wideo i Wzmacniacz Głośności', extensionDescription: 'Steruj prędkością do 16x i głośnością do 600%. Prosto, szybko i lekko.',
        settings: 'Ustawienia', speed: 'Prędkość', videoSpeed: 'Prędkość wideo', volumeBoost: 'Wzmocnienie Głośności', nowPlaying: 'Teraz Odtwarzane', loading: 'Ładowanie…', checkingPage: 'Sprawdzanie strony…', unknownTab: 'Nieznana karta', cannotAccessPage: 'Brak dostępu do tej strony', noVideo: 'Brak wideo na tej stronie', resolution: 'Rozdzielczość', detectingResolution: 'Wykrywanie rozdzielczości…', settingsTitle: 'Ustawienia Yeedio', savedVideoSpeed: 'Zapisana prędkość (0,25x – 16x)', savedVolumeBoost: 'Zapisana głośność (0% – 600%)', saveSettings: 'Zapisz ustawienia', settingsSaved: 'Ustawienia zapisane.', keyboardShortcuts: 'Skróty klawiaturowe', openYeedio: 'otwórz Yeedio', adjustSpeed: 'zmniejsz / zwiększ prędkość', customizeShortcuts: 'Dostosuj skróty głośności na', increaseSpeedCommand: 'Zwiększ prędkość (+0,25x)', decreaseSpeedCommand: 'Zmniejsz prędkość (-0,25x)', increaseVolumeCommand: 'Zwiększ głośność (+10%)', decreaseVolumeCommand: 'Zmniejsz głośność (-10%)'
    },
    sv: {
        extensionName: 'Yeedio: Videohastighet & Volymförstärkare', extensionDescription: 'Styr videohastighet upp till 16x och volym upp till 600%. Enkelt, snabbt och lätt.',
        settings: 'Inställningar', speed: 'Hastighet', videoSpeed: 'Videohastighet', volumeBoost: 'Volymförstärkning', nowPlaying: 'Spelas Nu', loading: 'Laddar…', checkingPage: 'Kontrollerar sidan…', unknownTab: 'Okänd flik', cannotAccessPage: 'Kan inte komma åt sidan', noVideo: 'Ingen video på sidan', resolution: 'Upplösning', detectingResolution: 'Identifierar upplösning…', settingsTitle: 'Yeedio-inställningar', savedVideoSpeed: 'Sparad videohastighet (0,25x – 16x)', savedVolumeBoost: 'Sparad volym (0% – 600%)', saveSettings: 'Spara inställningar', settingsSaved: 'Inställningarna har sparats.', keyboardShortcuts: 'Kortkommandon', openYeedio: 'öppna Yeedio', adjustSpeed: 'minska / öka hastighet', customizeShortcuts: 'Anpassa volymkommandon på', increaseSpeedCommand: 'Öka videohastigheten (+0,25x)', decreaseSpeedCommand: 'Minska videohastigheten (-0,25x)', increaseVolumeCommand: 'Öka volymen (+10%)', decreaseVolumeCommand: 'Minska volymen (-10%)'
    },
    th: {
        extensionName: 'Yeedio: ควบคุมความเร็ววิดีโอและเพิ่มเสียง', extensionDescription: 'ปรับความเร็ววิดีโอได้ถึง 16x และเสียงถึง 600% ใช้ง่าย รวดเร็ว และเบา',
        settings: 'การตั้งค่า', speed: 'ความเร็ว', videoSpeed: 'ความเร็ววิดีโอ', volumeBoost: 'เพิ่มเสียง', nowPlaying: 'กำลังเล่น', loading: 'กำลังโหลด…', checkingPage: 'กำลังตรวจสอบหน้า…', unknownTab: 'แท็บที่ไม่รู้จัก', cannotAccessPage: 'ไม่สามารถเข้าถึงหน้านี้', noVideo: 'ไม่มีวิดีโอในหน้านี้', resolution: 'ความละเอียด', detectingResolution: 'กำลังตรวจหาความละเอียด…', settingsTitle: 'การตั้งค่า Yeedio', savedVideoSpeed: 'ความเร็ววิดีโอที่บันทึก (0.25x – 16x)', savedVolumeBoost: 'ระดับเสียงที่บันทึก (0% – 600%)', saveSettings: 'บันทึกการตั้งค่า', settingsSaved: 'บันทึกการตั้งค่าแล้ว', keyboardShortcuts: 'แป้นพิมพ์ลัด', openYeedio: 'เปิด Yeedio', adjustSpeed: 'ลด / เพิ่มความเร็ว', customizeShortcuts: 'ปรับแต่งปุ่มลัดเสียงที่', increaseSpeedCommand: 'เพิ่มความเร็ววิดีโอ (+0.25x)', decreaseSpeedCommand: 'ลดความเร็ววิดีโอ (-0.25x)', increaseVolumeCommand: 'เพิ่มระดับเสียง (+10%)', decreaseVolumeCommand: 'ลดระดับเสียง (-10%)'
    },
    vi: {
        extensionName: 'Yeedio: Tốc độ Video & Tăng Âm lượng', extensionDescription: 'Điều chỉnh tốc độ video đến 16x và âm lượng đến 600%. Đơn giản, nhanh và nhẹ.',
        settings: 'Cài đặt', speed: 'Tốc độ', videoSpeed: 'Tốc độ video', volumeBoost: 'Tăng Âm lượng', nowPlaying: 'Đang Phát', loading: 'Đang tải…', checkingPage: 'Đang kiểm tra trang…', unknownTab: 'Tab không xác định', cannotAccessPage: 'Không thể truy cập trang này', noVideo: 'Không có video trên trang này', resolution: 'Độ phân giải', detectingResolution: 'Đang phát hiện độ phân giải…', settingsTitle: 'Cài đặt Yeedio', savedVideoSpeed: 'Tốc độ video đã lưu (0,25x – 16x)', savedVolumeBoost: 'Âm lượng đã lưu (0% – 600%)', saveSettings: 'Lưu cài đặt', settingsSaved: 'Đã lưu cài đặt.', keyboardShortcuts: 'Phím tắt', openYeedio: 'mở Yeedio', adjustSpeed: 'giảm / tăng tốc độ', customizeShortcuts: 'Tùy chỉnh phím tắt âm lượng tại', increaseSpeedCommand: 'Tăng tốc độ video (+0,25x)', decreaseSpeedCommand: 'Giảm tốc độ video (-0,25x)', increaseVolumeCommand: 'Tăng âm lượng (+10%)', decreaseVolumeCommand: 'Giảm âm lượng (-10%)'
    }
};

for (const [locale, strings] of Object.entries(locales)) {
    const expectedKeys = Object.keys(locales.en);
    const missingKeys = expectedKeys.filter((key) => !strings[key]);
    if (missingKeys.length) {
        throw new Error(`${locale} is missing: ${missingKeys.join(', ')}`);
    }
    if (strings.extensionName.length > 75) {
        throw new Error(`${locale} extensionName exceeds 75 characters`);
    }
    if (strings.extensionDescription.length > 132) {
        throw new Error(`${locale} extensionDescription exceeds 132 characters`);
    }

    const directory = new URL(`../_locales/${locale}/`, import.meta.url);
    await mkdir(directory, { recursive: true });
    const messages = Object.fromEntries(
        Object.entries(strings).map(([key, message]) => [key, { message }])
    );
    await writeFile(new URL('messages.json', directory), `${JSON.stringify(messages, null, 4)}\n`, 'utf8');
}

console.log(`Generated ${Object.keys(locales).length} locales.`);
